version: '3'
services:
    frontend:
        build: ./
        depends_on: 
            - db
        ports:
            - "8001:80"
        volumes:
            - ./frontend/:/var/www/html 
    db:
        image: mysql:5.6
        volumes:
            - ./sql/:/docker-entrypoint-initdb.d/
        environment: 
            MYSQL_ROOT_PASSWORD: 'root' 
            MYSQL_USER: 'root'
